### ISSUE TITLE
reordering question lines

### ISSUE THREAD

**Issue by oliverglanz** [EzerIT/BibleOL#42]
This is not urgent. But several instructors have mentioned that it would be nice to define the order in which features are being presented to students during exercises. Right now the order is fixed. For example:
<img width="868" alt="image" src="https://github.com/EzerIT/BibleOL/assets/8409738/eba54af4-36a9-4121-8b48-ea60b3adb391">

Here we have the order stem => tense => person => number => gender.

Some instructors want a different order. For example: person => number => gender ...

Solution: Could one add a column in the feature selection that allows for the preferred order of feature appearance?

<img width="751" alt="image" src="https://github.com/EzerIT/BibleOL/assets/8409738/f87b8a99-4eba-4726-b461-517e13db7e75">

**Comment by tmccormack165** [comment]
Hi Oliver, thank you for your design, I think this is a great idea, and I have added it to my tasks.

**Comment by ernstboogert** [comment]
Good point Oliver, we will try to design a convenient solution to this problem... Thanks!

**Comment by tmccormack165** [comment]
The frontend design is complete:
<img width="743" alt="Screenshot 2024-02-19 at 11 38 36 AM" src="https://github.com/EzerIT/BibleOL/assets/60988784/08b2c238-e0f1-4c88-9a91-83174da8960e">

**Comment by oliverglanz** [comment]
Very nice!

**Comment by tmccormack165** [comment]
This task is now completed. A teacher can order the features presented to the student. If a teacher does not order a specific feature, that feature will be pushed to the bottom of the exercise panel. If a teacher does not order any features, then the features will be ordered as they appear on the feature select table.

Here I order **lexeme** ahead of **part_of_speech**, before **part_of_speech** would come first because it is ahead of **lexeme** in the feature select table.
<img width="1279" alt="Screenshot 2024-02-20 at 6 00 42 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/601163a8-4dce-4b02-bb67-c9d8401bb66c">

However, after this enhancement you can see that **lexeme** appears first when running an exercise.
<img width="869" alt="Screenshot 2024-02-20 at 6 02 04 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/17b432f0-3c94-4a0d-a3e2-6aa2d1284221">
