### ISSUE TITLE
Add easy execution of a newly edited exercise

### ISSUE THREAD

**Issue by oz1cz** [EzerIT/BibleOL#6]
Add a button to test a newly edited exercise on the exercise editing page. (You can, for example, add a "not scoring" parameter to the execution of an exercise and use that parameter to modify the text on the buttons that terminate the execution. This can also be used to modify the same buttons when an exercise is executed by a person who is not logged in.)

**Comment by tmccormack165** [comment]
This issue is now resolved. There is now a button called "Test Exercise" that will allow a teacher to test an exercise while they are creating it. 

<img width="1281" alt="Screenshot 2024-02-27 at 11 49 55 AM" src="https://github.com/EzerIT/BibleOL/assets/60988784/a3ddef0c-46d9-4e32-889f-7190770db5d3">




After "Test Exercise" is pressed the exercise is displayed with the most recent parameters:
<img width="879" alt="Screenshot 2024-02-27 at 12 00 38 PM" src="https://github.com/EzerIT/BibleOL/assets/60988784/b1eb6603-1473-4308-beac-fb957412a195">


Users can press "Back" to continue editing the exercise.
