### ISSUE TITLE
Error in the Copy/Paste process making copying/pasting impossible.

### ISSUE THREAD

**Issue by oliverglanz** [EzerIT/BibleOL#77]
When copying a file from a folder that belongs to another user, BOL has stopped functioning. When one moves into one's own folder and chooses to insert the copied file, the following error message appears

<img width="1271" alt="Screenshot 2024-08-26 at 21 24 42" src="https://github.com/user-attachments/assets/e69bb4e7-e8e0-4f5b-bd26-3daea385b65d">

This error is crucial as users can no longer use exercises that were created by other users.

Users can also not download exercises and then upload the downloaded exercises into their own folder. The following error message appears:
<img width="403" alt="Screenshot 2024-08-26 at 21 45 08" src="https://github.com/user-attachments/assets/08fdeadf-1e49-4c3e-99f2-ee9d78d1a46f">

**Comment by tmccormack165** [comment]
This issue is now resolved.

**Comment by oliverglanz** [comment]
That was a quick fix! Thanks so much. Do you know what caused it?

**Comment by tmccormack165** [comment]
The problem was when the application was trying to insert the copied exercise into the database. I needed to cast the string that represented the time limit to an integer.
<img width="922" alt="Screenshot 2024-08-27 at 7 20 09 AM" src="https://github.com/user-attachments/assets/97a4547a-d6e2-4473-9c17-d3145cf5df35">
